### ISSUE TITLE
Upgrade instructions from 0.9.1.4 to 0.9.2.0

### ISSUE THREAD

**Issue by mindscratch** [mesos/kafka#132] opened 2015-10-14 09:45 UTC
I'm currently running 0.9.1.4 and was wondering what steps I'd have to take to upgrade to 0.9.2.0.

It looks like I'd put the new JAR on a server, but do I just need to restart brokers or do I need I remove and add them again?

**Comment by mindscratch** [comment] 2015-11-09 17:28
Looking closer, it looks I can just restart the scheduler and that's it. Am I missing anything?

**Comment by dmitrypekar** [comment] 2015-11-09 17:50
Hi @mindscratch 

You are right. Currently by design you can just stop old scheduler and start a new one. You can also restart each broker for changes in Executor to apply.

Please note: if you are going to do this on prod, note somewhere the current location of brokers to be able to restart them on the same set of slaves. For now the scheduler does support slave stickiness function, but your version could potentially not.

Also please close this ticket.

**Comment by mindscratch** [comment] 2015-11-09 22:24
@dmitrypekar I'm currently running 0.9.1.4. Does that version support slave stickiness? If not, how would/could I get the brokers to start on the same hosts as before? Also, to do the restart, would I just restart a single broker, wait a minute, restart the next, etc until all have been restarted? Each of my topics has 3 or more replicas, so I believe I won't lose data.

**Comment by dmitrypekar** [comment] 2015-11-10 13:06
@mindscratch yes, stickiness is supported starting from 0.9.1.1.
Yes, imho, it is more safe to restart brokers one-by-one.
I suppose, that log.dirs is configured to be outside Mesos sandbox? So restarting would use the same log.dirs?

**Comment by mindscratch** [comment] 2015-11-10 13:17
yes log.dirs is configured outside the sandbox.

On Tue, Nov 10, 2015 at 8:06 AM, dmitrypekar notifications@github.com
wrote:

> @mindscratch https://github.com/mindscratch yes, stickiness is
> supported starting from 0.9.1.1.
> Yes, imho, it is more safe to restart brokers one-by-one.
> I suppose, that log.dirs is configured to be outside Mesos sandbox? So
> restarting would use the same log.dirs?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mesos/kafka/issues/132#issuecomment-155414582.

## 

https://github.com/mindscratch
https://www.google.com/+CraigWickesser
https://twitter.com/mind_scratch
https://twitter.com/craig_links

**Comment by dmitrypekar** [comment] 2015-11-10 13:42
In that case the above upgrade scenario should work fine. Please report about the results and close the ticket.

**Comment by dmitrypekar** [comment] 2015-11-17 11:58
Closing the ticket as outdated.

**Closed as completed by dmitrypekar** 2015-11-17 11:58 UTC
