### ISSUE TITLE
CLI does produce a WARN if $TERM is not set

### ISSUE THREAD

**Issue by sargun** [mesos/kafka#129] opened 2015-10-13 21:22 UTC
Example:

```
# TERM= dcos kafka topic
Topic management commands
Usage: topic <command>

Commands:
  list       - list topics
  add        - add topic
  update     - update topic
  rebalance  - rebalance topics

Run `help topic <command>` to see details of specific command

tput: No value for $TERM and no -T specified
Error: command required
```

**Comment by dmitrypekar** [comment] 2015-10-13 21:34
@sargun

`tput: No value for $TERM and no -T specified` is actually a warning.

Error is - 'Error: command required'
You should use `dcos kafka topic list|add|update|rebalance` instead.

**Comment by dmitrypekar** [comment] 2015-10-13 21:36
Need to verify about this WARN. This should be already fixed in recent dcos-kafka project.

**Comment by sargun** [comment] 2015-10-14 17:03
Yeah, although it's a warning, it interferes with some people's programmatic usage of the Kafka CLI -- any reason not to fall back to a dumb terminal (80 cols, no colours, etc..) if the variable isn't set?

**Comment by dmitrypekar** [comment] 2015-10-14 18:44
This should be already fixed in latest dcos-kafka build. Need to recheck.

**Comment by dmitrypekar** [comment] 2015-11-18 14:30
@sargun 
For now I can't reproduce it with dcos-kafka (it contains a fix).
Could you please, recheck this and close the ticket?

**Closed as completed** 2015-11-18 16:38 UTC
